In [31]:
from tensorflow.keras.preprocessing.text import one_hot

In [32]:
## Sentences
sent=['the glass of milk',
   'the glass of juice',
   'the cup of tea',
   'I am a good boy',
   'I am a good developer',
   'understand the meaning of words',
   'your videos are good']

In [33]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [34]:
## Define the vocabulary size
voc_size=10000


In [35]:
## One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]


In [36]:
one_hot_repr

[[6431, 8979, 5065, 6708],
 [6431, 8979, 5065, 1520],
 [6431, 5168, 5065, 2960],
 [2141, 4469, 9047, 3340, 2371],
 [2141, 4469, 9047, 3340, 874],
 [2945, 6431, 597, 5065, 1477],
 [3236, 7820, 8202, 3340]]

In [37]:
## word embedding representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [38]:
import numpy as np

In [39]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6431 8979 5065 6708]
 [   0    0    0    0 6431 8979 5065 1520]
 [   0    0    0    0 6431 5168 5065 2960]
 [   0    0    0 2141 4469 9047 3340 2371]
 [   0    0    0 2141 4469 9047 3340  874]
 [   0    0    0 2945 6431  597 5065 1477]
 [   0    0    0    0 3236 7820 8202 3340]]


In [46]:
## feature representation
dim=10

In [47]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))

In [48]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step


array([[[ 4.39803675e-03,  2.58507617e-02,  3.66299227e-03,
         -5.55159897e-03,  1.74266435e-02,  2.04405077e-02,
         -3.20666656e-02, -2.37574931e-02,  2.59448923e-02,
         -3.36392298e-02],
        [ 4.39803675e-03,  2.58507617e-02,  3.66299227e-03,
         -5.55159897e-03,  1.74266435e-02,  2.04405077e-02,
         -3.20666656e-02, -2.37574931e-02,  2.59448923e-02,
         -3.36392298e-02],
        [ 4.39803675e-03,  2.58507617e-02,  3.66299227e-03,
         -5.55159897e-03,  1.74266435e-02,  2.04405077e-02,
         -3.20666656e-02, -2.37574931e-02,  2.59448923e-02,
         -3.36392298e-02],
        [ 4.39803675e-03,  2.58507617e-02,  3.66299227e-03,
         -5.55159897e-03,  1.74266435e-02,  2.04405077e-02,
         -3.20666656e-02, -2.37574931e-02,  2.59448923e-02,
         -3.36392298e-02],
        [ 4.33766581e-02, -3.86995450e-02,  4.13133763e-02,
         -2.52709519e-02,  2.57136486e-02, -4.23732400e-02,
          2.97456868e-02,  1.28420927e-02, -3.604800

In [53]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[ 0.00439804,  0.02585076,  0.00366299, -0.0055516 ,
          0.01742664,  0.02044051, -0.03206667, -0.02375749,
          0.02594489, -0.03363923],
        [ 0.00439804,  0.02585076,  0.00366299, -0.0055516 ,
          0.01742664,  0.02044051, -0.03206667, -0.02375749,
          0.02594489, -0.03363923],
        [ 0.00439804,  0.02585076,  0.00366299, -0.0055516 ,
          0.01742664,  0.02044051, -0.03206667, -0.02375749,
          0.02594489, -0.03363923],
        [ 0.00439804,  0.02585076,  0.00366299, -0.0055516 ,
          0.01742664,  0.02044051, -0.03206667, -0.02375749,
          0.02594489, -0.03363923],
        [ 0.04337666, -0.03869954,  0.04131338, -0.02527095,
          0.02571365, -0.04237324,  0.02974569,  0.01284209,
         -0.03604801, -0.04647538],
        [-0.04865873,  0.00881768,  0.01071358, -0.01427337,
          0.04085478,  0.01372011,  0.01782722,  0.01579172,
         -0.02925852,  0.03534268],
        [-0.00656797,  0.0413884 ,  0.02095029, -0.0